# Generated by Django 3.1.5 on 2021-01-31 14:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0008_orderproduct'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderProduct',
            new_name='CartProduct',
        ),
    ]
