# Generated by Django 3.1.5 on 2021-01-31 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_order_orderproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='location',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
    ]
