# Generated by Django 3.1.5 on 2021-01-31 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_auto_20210131_1704'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iban', models.CharField(max_length=40)),
                ('sum', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='iban',
        ),
        migrations.AddField(
            model_name='order',
            name='bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.bankaccount'),
        ),
    ]
